services:
  app:
    build: .
    container_name: scala-2
    ports:
      - "8050:8050"
    env_file:
      - .env          # 👈 tell Docker to load .env
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
